### PR TITLE
- Update Pdfium so libs (fixing pdfium so libs, regarding Android device version 23)

### PR DESCRIPTION
**Pull request by lion1988dev**
- Update new so header files
- Update PdfiumCore regarding new so libs

### CODE REVIEW

**Comment by johngray1965** [comment]
Can you tell me where you got the new libs?  I'd like to verify them.

**Comment by lion1988dev** [comment]
Hello, @johngray1965 

Regarding so libs:
1. Im using this project https://github.com/bblanchon/pdfium-binaries for compiling pdfium libs
2. I have added new patch which fixed issue for Android API 23 and compiled so libs

**Comment by lion1988dev** [comment]
@johngray1965 Here`s my new patch, which i created for configure compiling so libs:
wordpad_2024-01-16_16-39-14

**Comment by lion1988dev** [comment]
Hello, @johngray1965
Any news regarding MR?

**Comment by johngray1965** [comment]
Sorry for the delay, I was very busy with other things, but now I need a change myself, so...

**Comment by johngray1965** [comment]
Did you run the tests?   There are test failures.

**Comment by johngray1965** [comment]
Yeah, something is not right.   Before this I can run all the tests on multiple devices, nothing is working now.

**Comment by johngray1965** [comment]
I reverted the merge of the PR, but its failing badly.

**Comment by lion1988dev** [comment]
@johngray1965 Hello, 
Let me check it all again, i have tested it before, on many devices and it worked fine, but probably i made mistakes, when created MR on your remote, i need couple of days for testing and i will come back to you, thanks

**Comment by lion1988dev** [comment]
> Yeah, something is not right. Before this I can run all the tests on multiple devices, nothing is working now.

Which devices, you are using for test, i meant architecture (arm, x86 etc)?

**Comment by johngray1965** [comment]
Can you submit a new PR, one is in a funky state when it was merge and reverted.

**Comment by lion1988dev** [comment]
@johngray1965 Created new PR https://github.com/johngray1965/PdfiumAndroidKt/pull/16, you can check

**Pull request merged**
